### ISSUE TITLE
clear method triggers  px-file-upload-files-changed

### ISSUE THREAD

**Issue by rupeshpadhye** [PredixDev/px-file-upload#21] opened 2018-09-06 08:49 UTC
`clear` method should reset the component to its original state . but currently   `px-file-upload-files-changed` event is emitted explicitly

**Comment by evanjd** [comment] 2018-09-06 10:21
This is intended behaviour. `px-file-upload-files-changed` whenever the `files` array changes. `clear()` empties the file array, so it's logical it would fire the event indicating that `files` has changed.

If this causing problems for you, just ignore it in your event handler, eg.

```javascript
document
  .querySelector("px-file-upload")
  .addEventListener("px-file-upload-files-changed", evt => {
    // Skip if triggered by clear
    if (evt.detail.length === 0) return false;
    // Do whatever you want to do here.
    console.log('Got a file!');
  });
```

**Comment by rupeshpadhye** [comment] 2018-09-06 10:39
@evanjd  Component consumer have to write unnecessary `IF` condition 
 I think intention of public `clear` method  is to restore the file upload component to its default empty state. since `clear` method is called  from Programmatically, consumer knows the impact of it so triggering an custom event is not required 
:bulb: It makes sense if you are calling `_notifyFilesChanged` from `_removeFile` method but not from `clear`
 I would like to know the user case where it is required

**Comment by evanjd** [comment] 2018-09-06 11:08
> consumer knows the impact of it so triggering an custom event is not required

I see your point, but we're not implementing this from scratch, we're changing an existing behaviour. This is breaking change, trivial as it may be. I think there's justifications for both behaviours (the one you want and the current behaviour), why risk it when it can be trivially managed in your case with a 1-liner?

> I would like to know the user case where it is required

Off the cuff: User has implemented their own clear all button that invokes `clear()`. Their implementation listens to the `px-file-upload-files-changed` event and adds/modifies/removes files from server by inspecting the event's `detail` property.

**Comment by evanjd** [comment] 2018-09-11 01:42
No comment for a few days - closing. Conversation isn't locked so feel free to reply if you have any further questions or concerns.

**Closed as completed by evanjd** 2018-09-11 01:42 UTC
Labels: wontfix
